apiVersion: apps/v1
kind: Deployment
metadata:
    name: build
    labels:
        app: build
spec:
    replicas: 1
    selector:
        matchLabels:
            app: build
    template:
        metadata:
            labels:
                app: build
        spec:
            containers:
            -   name: jenkins
                image: bensonre/myjenkins
            restartPolicy: Always  
