kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deploy
rules:
- apiGroups: [""]
  resources: ["pods", "replicasets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec","replicasets/exec", "deployments/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["create","delete","get","list","patch","update","watch"]
