credentials:
    system:
      domainCredentials:
      - credentials:
        - string:
            description: "jenkins webhook token"
            id: "4c65c3ce-abf9-498d-9cb6-985c27c2f553"
            scope: GLOBAL
            secret: ${GITHUB_WEBHOOK_TOKEN}
        - string:
            description: "Slack Token"
            id: "slack-token"
            scope: GLOBAL
            secret: ${SLACK_TOKEN}
        - usernamePassword:
            description: "docker hub"
            id: "docker_hub_credentials"
            password: ${DOCKER_HUB_TOKEN}
            scope: GLOBAL
            username: ${DOCKER_HUB_USERNAME}
jenkins:
  systemMessage: "Jenkins Configuration as Code Example"
  numExecutors: 1
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
    - kubernetes:
        connectTimeout: 5
        containerCapStr: "10"
        credentialsId: "5ae1df0f-e2d2-42a9-bf0e-f51b8f9291d8"
        jenkinsUrl: "http://10.100.201.179:8080"
        maxRequestsPerHostStr: "32"
        name: "kubernetes"
        namespace: "jank8s"
        readTimeout: 15
        serverCertificate: |2-
          -----BEGIN CERTIFICATE-----
          MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          cm5ldGVzMB4XDTIwMDkxNjE5MDk1MloXDTMwMDkxNDE5MDk1MlowFTETMBEGA1UE
          AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALA0
          u5VFRGOaoxuEajXvQuRr0Likg5xqp0AiTXvmRkmRfjoYzTvi3a8V+ft9rASSNAN5
          3t6d8Akye0ksCgB5ntOMOvIjeWogaXSRplCZxpW7yrgNrM1FhiUxM7zfsrgvI8gB
          L0MtNQSgkKQxcVk8wY6ukMV+g/j117vVPLFJ+26b+qpLQVtqfcrCAx3UybF202OY
          k3KDdZq3FFvuIa8AU5i76YsS9GrCZVumz0rI0z81mN2mPSCuZsiX/sAelH0vfG19
          ljRDLSpVsk1yYNh1MT1trLyNT3auEGD2VORqNc+m/ip06HavNYzAddiOqYVVUGy3
          7Et5DbPE6sq4+BrHYDkCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
          /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAATPNGTJrK25S/XENU1i/3XsQgLA
          BU7LZ9K9X1sicVMtXZCLJura/NV5RqEBUztnlzVXUJ0WftfK6F8oGNQe+n6lE/i3
          zfG585FyjnrBdyFwKgf8OJwTNasw6lNe5ld1CYvc0Q5C3Rayk+8bTU8VeQquPFug
          7kX0wabnuJsFmanhXwQR82TrDlcVDeIYJNtnr04UqxzEr7Ky1qPcX2z0U9rHCrVh
          /vsQ50euyeOFaPiX9T1fFxeFOTM4pg1kB+TvT+LJPRNz/FqnEd8OeNEk2wvtmdo2
          Ekfas76dgD6Jq/sK/qW7yV+bWPWlRUJkZ5SJJZ68W1lmO2dgzRoFF5Emwvs=
          -----END CERTIFICATE-----
        serverUrl: "https://3A24A451782BEA5F4471208F7D9A585B.gr7.us-west-2.eks.amazonaws.com"
unclassified:
    gitHubPluginConfig:
        configs:
        -  name: "default"
           credentialsId: "4c65c3ce-abf9-498d-9cb6-985c27c2f553"
        hookUrl: "${MY_JENKINS_PROXY}"
    slackNotifier:
      botUser: false
      room: "#jank8sproject-2"
      sendAsText: false
      teamDomain: "${SLACK_TEAM_DOMAIN}"
      tokenCredentialId: "slack-token"
    email-ext:
      adminRequiredForTemplateTesting: false
      allowUnregisteredEnabled: true
      charset: "UTF-8"
      debugMode: false
      defaultBody: |-
        $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
  
        Check console output at $BUILD_URL to view the results.
      defaultContentType: "text/plain"
      defaultRecipients: "${DEFAULT_RECIPIENTS}"
      defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
      defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
      mailAccount:
        address: "address not configured yet <nobody@nowhere>"
        smtpHost: "${SMTP_HOST}"
        smtpPassword: "${SMTP_PASSWORD}"
        smtpPort: "${SMTP_PORT}"
        smtpUsername: "${SMTP_USERNAME}"
        useSsl: true
      maxAttachmentSize: -1
      maxAttachmentSizeMb: -1
      precedenceBulk: false
      smtpPassword: "${SMTP_PASSWORD}"
      watchingEnabled: false
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  maven:
    installations:
    - name: "maven3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.5.4"
jobs:
  - script: >
      pipelineJob('mvn-exists-test') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                tools {
                // Install the Maven version configured as "M3" and add it to the path.
                  maven "maven3"
                }
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                      sh "mvn -v"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
  - script: >
      pipelineJob('Http-server') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/200803-java-devops/http-server.git')
                }
                branch('*/master')
              }
            }
            lightweight()
          }
        }
      }