credentials:
    system:
      domainCredentials:
      - credentials:
        - string:
            description: "jenkins webhook token"
            id: "4c65c3ce-abf9-498d-9cb6-985c27c2f553"
            scope: GLOBAL
            secret: ${GITHUB_WEBHOOK_TOKEN}
        - string:
            description: "Slack Token"
            scope: GLOBAL
            secret: ${SLACK_TOKEN}
        - usernamePassword:
            description: "docker hub"
            id: "docker_hub_credentials"
            password: ${DOCKER_HUB_TOKEN}
            scope: GLOBAL
            username: ${DOCKER_HUB_USERNAME}
        - string:
            description: "Slack Token"
            scope: GLOBAL
            secret: ${SLACK_TOKEN}
jenkins:
  systemMessage: "Jenkins Configuration as Code Example"
  numExecutors: 1
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
        connectTimeout: 5
        containerCapStr: "10"
        #change jenkins url
        jenkinsUrl: "http://${JENKINS_SERVICE_SERVICE_HOST}:${JENKINS_SERVICE_SERVICE_PORT}" 
        maxRequestsPerHostStr: "32"
        name: "kubernetes"
        readTimeout: 15
        serverUrl: "https://kubernetes.docker.internal:6443/"
        skipTlsVerify: true
unclassified:
    gitHubPluginConfig:
        configs:
        -  name: "default"
           credentialsId: "4c65c3ce-abf9-498d-9cb6-985c27c2f553"
        hookUrl: "${MY_JENKINS_PROXY}"
    slackNotifier:
      botUser: false
      sendAsText: false
      teamDomain: "revaturetrain-cx22851"
      tokenCredentialId: "${SLACK_TOKEN}"
    email-ext:
      adminRequiredForTemplateTesting: false
      allowUnregisteredEnabled: true
      charset: "UTF-8"
      debugMode: false
      defaultBody: |-
        $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
  
        Check console output at $BUILD_URL to view the results.
      defaultContentType: "text/plain"
      defaultRecipients: "downward150@gmail.com"
      defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
      defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.AlwaysTrigger"
      - "hudson.plugins.emailext.plugins.trigger.PreBuildTrigger"
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
      mailAccount:
        address: "address not configured yet <nobody@nowhere>"
        smtpHost: "smtp.gmail.com"
        smtpPassword: "${EMAIL_PASSWORD}"
        smtpPort: "465"
        smtpUsername: "downward150@gmail.com"
        useSsl: true
      maxAttachmentSize: -1
      maxAttachmentSizeMb: -1
      precedenceBulk: false
      smtpPassword: "${EMAIL_PASSWORD}"
      watchingEnabled: false
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  maven:
    installations:
    - name: "maven3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.5.4"
jobs:
  - script: >
      pipelineJob('mvn-exists-test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/200803-java-devops/JanK8s.git')
                }
                branch('*/dev')
              }
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Http-server') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/200803-java-devops/JanK8s.git')
                }
                branch('*/dev')
              }
            }
            lightweight()
          }
        }
      }