credentials:
    system:
      domainCredentials:
      - credentials:
        - string:
            description: "jenkins webhook token"
            id: "4c65c3ce-abf9-498d-9cb6-985c27c2f553"
            scope: GLOBAL
            secret: ${GITHUB_WEBHOOK_TOKEN}
        - string:
            description: "Slack Token"
            scope: GLOBAL
            secret: ${SLACK_TOKEN}
        - usernamePassword:
            description: "docker hub"
            id: "docker_hub_credentials"
            password: ${DOCKER_HUB_TOKEN}
            scope: GLOBAL
            username: ${DOCKER_HUB_USERNAME}
        - string:
            description: "Slack Token"
            scope: GLOBAL
            secret: ${SLACK_TOKEN}
jenkins:
  systemMessage: "Jenkins Configuration as Code Example"
  numExecutors: 1
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
unclassified:
    gitHubPluginConfig:
        configs:
        -  name: "default"
           credentialsId: "4c65c3ce-abf9-498d-9cb6-985c27c2f553"
        hookUrl: "${MY_JENKINS_PROXY}"
    slackNotifier:
      botUser: false
      sendAsText: false
      teamDomain: "revaturetrain-cx22851"
      tokenCredentialId: "${SLACK_TOKEN}"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  maven:
    installations:
    - name: "maven3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.5.4"
jobs:
  - script: >
      pipelineJob('mvn-exists-test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/200803-java-devops/JanK8s.git')
                }
                branch('*/dev')
              }
            }
            lightweight()
          }
        }
      }
  - script: >
      pipelineJob('Http-server') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/200803-java-devops/JanK8s.git')
                }
                branch('*/dev')
              }
            }
            lightweight()
          }
        }
      }