apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
spec:
    type: NodePort
    selector:
        app: build
    ports:
        - port: 8080
          name: jenkins
          targetPort: 8080
          nodePort: 30000
        - port: 50000
          name: slave
          targetPort: 50000
          nodePort: 30001

