apiVersion: v1
kind: Service
metadata:
    namespace: jank8s
    name: delivery-service
spec:
    type: NodePort
    selector:
        app: build
    ports:
        - port: 8085
          name: sample1
          targetPort: 8085
          nodePort: 30005