apiVersion: v1
kind: Service
metadata:
    namespace: jank8s
    name: delivery-service
spec:
    type: NodePort
    selector:
        app: delivery
    ports:
        - port: 8086
          name: nodejs-server
          targetPort: 8086
          nodePort: 30006