apiVersion: v1
kind: Service
metadata:
    name: sample2-service
spec:
    type: NodePort
    selector:
        app: sample2
    ports:
        - port: 8080
          name: sample
          targetPort: 8080
          nodePort: 30004