apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: jank8s
    name: sample2
    labels:
        app: sample2
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sample2
    template:
        metadata:
            labels:
                app: sample2
        spec:
            containers:
            -   name: sample2
                image: jank8s/jenkins-sample2
                imagePullPolicy: Always
            restartPolicy: Always